### ISSUE TITLE
Rename repo to cucumber-wire-ruby

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-ruby-wire#5]
This is to conform with the naming standard used for other libraries such as `cucumber-expressions-[ruby,java,javascript,etc]`.

The gem name should stay the same, just `cucumber-wire`

**Comment by mattwynne** [comment]
Go for it!

That would assume we're going to implement the wire protocol on other platforms - are there any plans to do that?

**Comment by aslakhellesoy** [comment]
Yes, cucumber/cucumber-jvm#1025

**Comment by andyb-ge** [comment]
Aslak, regarding your comment on the naming, this is not a Ruby gem. Rather, it is Java code. So, I renamed it to cucumber-wire-java. Let me know if this is OK.

**Comment by aslakhellesoy** [comment]
Ah brilliant @andyb-ge

**Comment by luke-hill** [comment]
This is done :D top tekkers all!
